// Expected parameters for the pipeline:
//   - OPENSHIFT_URL - RHMI cluster to target (https://...)
//   - OPENSHIFT_USERNAME - cluster-admin username
//   - OPENSHIFT_PASSWORD - cluster-admin password

pipeline {
  agent {
    dockerfile {
      dir 'containers/node'
      label 'psi_rhel8'
    }
  }
  options {
    timestamps()
    ansiColor('gnome-terminal')
  }
  environment {
    JUNIT_REPORT_STACK = '1'
    JUNIT_REPORT_PATH = 'report.xml'
    JUNIT_REPORT_NAME = 'Browser Tests'
  }
  stages {
    stage('Install dependencies') {
      steps {
        sh 'npm install'
        dir('browser') {
          sh 'npm install'
        }
      }
    }
    stage('Login with oc') {
      steps {
        wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[var: 'OPENSHIFT_PASSWORD', password: OPENSHIFT_PASSWORD]]]) {
          sh "oc login $OPENSHIFT_URL -u $OPENSHIFT_USERNAME -p ${OPENSHIFT_PASSWORD}"
        }
      }
    }
    stage('Test') {
      steps {
        dir('browser') {
          sh 'npm test -- --reporter mocha-jenkins-reporter || true'
          archiveArtifacts JUNIT_REPORT_PATH
          junit allowEmptyResults: true, testResults: JUNIT_REPORT_PATH
        }
      }
    }
  }
}