apiVersion: v1
data:
  graphqlEndpoint: /graphql
  syncServerUrl: >-
    ${SYNC_URL}
kind: ConfigMap
metadata:
  name: ${APP_NAME}-data-sync-binding
  ownerReferences:
    - apiVersion: mdc.aerogear.org/v1alpha1
      blockOwnerDeletion: false
      kind: MobileClient
      name: ${APP_NAME}
      uid: ${APP_UID}
