// Expected parameters for the pipeline:
//   - OPENSHIFT_URL - RHMI cluster to target (https://...)
//   - OPENSHIFT_KUBEADMIN_USERNAME - kubeadmin username
//   - OPENSHIFT_KUBEADMIN_PASSWORD - kubeadmin user password
//   - OPENSHIFT_USERNAME - Evals username
//   - OPENSHIFT_PASSWORD - Evals user password

pipeline {
  agent {
    dockerfile {
      dir 'containers/node'
      label 'psi_rhel8'
    }
  }
  options {
    timestamps()
    ansiColor('gnome-terminal')
  }
  environment {
    FIREBASE_SERVER_KEY = credentials('firebase-server-key')
    IOS_CERTIFICATE = credentials('ios-push-certificate')
    IOS_PASSPHRASE = credentials('ios-push-password')
    JUNIT_REPORT_STACK = '1'
    JUNIT_REPORT_PATH = 'report.xml'
    JUNIT_REPORT_NAME = 'Backend Tests'
  }
  stages {
    stage('Install dependencies') {
      steps {
        sh 'npm install'
        dir('backend') {
          sh 'npm install'
        }
      }
    }
    stage('Login with oc') {
      steps {
        wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[var: 'OPENSHIFT_KUBEADMIN_PASSWORD', password: OPENSHIFT_KUBEADMIN_PASSWORD]]]) {
          sh "oc login $OPENSHIFT_URL -u $OPENSHIFT_KUBEADMIN_USERNAME -p ${OPENSHIFT_KUBEADMIN_PASSWORD}"
        }
      }
    }
    stage('Test') {
      steps {
        dir('backend') {
          sh 'npm start -- --reporter mocha-jenkins-reporter || true'
          archiveArtifacts JUNIT_REPORT_PATH
          junit allowEmptyResults: true, testResults: JUNIT_REPORT_PATH
        }
      }
    }
  }
}
