# do not build for branch and tags
trigger: none

pr:
  branches:
    include:
      - master
  paths:
    include:
      - showcase/*

variables:
  BUILD_WORKSPACE: /tmp/showcase-$(Build.BuildNumber)

pool:
  vmImage: macos-latest
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 10.x
  - task: CmdLine@2
    inputs:
      script: npm install -g ionic@4 cordova@8
  - task: CmdLine@2
    inputs:
      workingDirectory: showcase/
      script: ./scripts/build.sh ios --clone-only --workspace $(BUILD_WORKSPACE)
  - task: CacheBeta@0
    inputs:
      key: node-modules | $(BUILD_WORKSPACE)/package-lock.json
      path: $(BUILD_WORKSPACE)/node_modules
  - task: CacheBeta@0
    inputs:
      key: cordova-plugins | $(BUILD_WORKSPACE)/package-lock.json | $(BUILD_WORKSPACE)/config.xml
      path: $(BUILD_WORKSPACE)/plugins
  - task: CmdLine@2
    inputs:
      workingDirectory: showcase/
      script: ./scripts/build.sh ios --workspace $(BUILD_WORKSPACE)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: showcase/apps/ionic-showcase.ipa
