apiVersion: aerogear.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: ${APP_NAME}-realm
  ownerReferences:
    - apiVersion: mdc.aerogear.org/v1alpha1
      blockOwnerDeletion: false
      kind: MobileClient
      name: ${APP_NAME}
      uid: ${APP_UID}
spec:
  clients:
    - bearerOnly: false
      clientAuthenticatorType: client-secret
      clientId: ${APP_NAME}-client
      enabled: true
      fullScopeAllowed: true
      name: ${APP_NAME}-client
      nodeReRegistrationTimeout: -1
      outputSecret: ${APP_NAME}-client-install-config
      publicClient: true
      redirectUris:
        - 'http://localhost*'
      standardFlowEnabled: true
      webOrigins:
        - 'http://localhost:8100'
        - '*'
  createOnly: true
  displayName: Realm for mobile app ${APP_NAME}
  enabled: true
  id: ${APP_NAME}-realm
  realm: ${APP_NAME}-realm
  users:
    - clientRoles:
        account:
          - manage-account
          - view-profile
        realm-management:
          - realm-admin
      emailVerified: false
      enabled: true
      firstName: ''
      lastName: ''
      outputSecret: ${APP_NAME}-admin-pass
      password: admin
      realmRoles:
        - offline_access
        - uma_authorization
      username: admin
