version: '3'

services:
  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
  metricsdb:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: metrics
      POSTGRES_PASSWORD: metrics
      POSTGRES_DB: metrics
  metrics:
    image: aerogear/aerogear-app-metrics:${METRICS_VERSION}
    ports:
      - "3000:3000"
    environment:
      PGHOST: metricsdb
      PGUSER: metrics
      PGPASSWORD: metrics
      PGDATABASE: metrics
    restart: always
    depends_on:
      - metricsdb
  upsdb:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ups
      POSTGRES_PASSWORD: ups
      POSTGRES_DB: ups
  ups:
    image: aerogear/unifiedpush-configurable-container:${UPS_VERSION}
    ports:
    - "8089:8080"
    environment:
      POSTGRES_SERVICE_HOST: upsdb
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_USER: ups
      POSTGRES_PASSWORD: ups
      POSTGRES_DATABASE: ups
    restart: always
    depends_on:
      - upsdb
  datasyncdb:
    image: postgres:9.6
    environment:
      POSTGRES_USER: sync
      POSTGRES_PASSWORD: sync
      POSTGRES_DB: sync
  datasync:
    image: aerogear/voyager-server-example-task:${DATASYNC_VERSION}
    ports:
      - "4000:4000"
    environment:
      DB_HOSTNAME: datasyncdb
      DB_USERNAME: sync
      DB_PASSWORD: sync
      DB_NAME: sync
    restart: always
    depends_on:
      - datasyncdb
